language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: bundle exec rake test
branches:
  only:
    - master
    - providers
gemfile:
  - Gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails3_2_3.gemfile
  - gemfiles/rails4.gemfile